[app]
name = "go-watcher"
version = "0.1"

[logger]
# trace debug info warn error fatal panic
level = "debug"
path = "./log"

[database]
type = ""
host = ""
port = 3306
user = ""
pass = ""
database = ""